version: '3.7'

services:
  vendas:
    image: hiranneri/vendas-service:prod
    container_name: vendas-app
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - SPRING_PROFILES_ACTIVE=prod

  financeiro:
    image: hiranneri/financeiro-service
    container_name: financeiro-app
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - SPRING_PROFILES_ACTIVE=qa

  operacoes:
    image: hiranneri/operacoes-service
    container_name: operacoes-app
    ports:
      - "8083:8083"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - SPRING_PROFILES_ACTIVE=qa




